language: r
sudo: false
cache:
  packages: true
  directories:
  - "$TRAVIS_BUILD_DIR/_book"
addons:
  apt:
    packages:
    - libssl-dev
r_github_packages:
- rmcelreath/rethinking
pandoc_version: 1.19.2.1
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- "./_build.sh"
- "./_deploy.sh"
notifications:
  slack:
    secure: EV4fM9uyxKCCsgiNe+tgD87hYgjtVbs+6cdyKywu2y1P+V59KBhSJ9PWoZVJwIMkcEAdTD8BxLk9Na3KGlkowDdfGyEMsVmy/+aKi+jXRRhJW3V7hmj7CWhWXM6nXdqm8iaACaAbJt8yP5HWLBjNcW0JSsA1u3XcH6hsuomnhbyi3MlYz6/qIbPYYl11m4Ok5VnI/v3NjDsrPTcHC7fXP5+fu1rN+WfFplYSP7/p3veXykWdcsB5fM+hovUrBue80w1ozdnppzlNjxH0BbeMHYRKIYPosXn3QS/vBf7t85bBm0GdibRd3aR7H+jVfeNnAH6dE3P7KPmv1bARNLRCcQXNAI+WC+L273XJnzA0wMQNay0CZkAlpLza8HwANtFSUvI8a1qRoB5kQaJzW1UDTiunmwO3BI4qjWdKOqiK4njVMB9LNL4+AFVDwJM1N7UV1f2ZzucVuKSITCI4CzpOyeLS3cc10xFtEiAOSWr4vOXqqDWfM33W9q3ROJ1881mZQbRKgwh3n+KxSp7KvDun9PXEhAZby/CMX88q+BEYjLyvjD5VmbqpTSRfk21Q91Ox6PCcA3Ia9MFP6rjoaoqp2DODYuLHGYhSgk/VehHjgiTj40xK23BKcmqmciOxPrWOpaVDe96n0qPQxJDzu094ytfaWWyL8cne7PKnog3BfKc=
env:
  global:
    secure: bN0/zgvEk/Tb1UypXaGxkG405x4/I9mNk0UJnFlado2Ej6HUf6qYr8WqGsGqp/b7qAbaG9gAlSUFfR30pt7A7yj+xqQcwLSor7F77VojgUUCW1Jy0oRPJYIZPpsf6h6YHp6iH6eBKO1axf+2fV7e7iMFy66E9ir9uS/oiWAd1iKyTD+Of2fLy4gupmKXaBg1C+G2OSaY6g0CM0yqfpZAIqJmhr6iICKGNFKwImrVtb8cODSP2HzNpNiqvaPvQ6uron76MwPDGAKladYZy5Ksbw1HpdCx6JFV5Y+pIq60DytALFBbUuTRqTZ7c4fmYurgGIZr7Eeg0EyG1wj6+062qvI2BhNesrgS0LjsdG/45rL2JJ5lKuOU+8ZpsdWgBegU6t64Y3ISFkmTFZxH2IQVZqUasYLSvIRpbIvqBo78pdow5JzmmiCIX3vCyBcEh/jCfdkw7bsPDjQY3O3rDn7MvV9TH8/yRH9+h3iVJBopr8p9WnOnkg7E1z6aHFIY2KKEmlOK9k6LlO+iCUAGPeMtcLafsBKmM2aRZIlleMeP8huUvD37F0vnZvPAD7OJdfFiF/MYfETW3LVijKKEme1nlQiF3ZVlMluP+mShUPH83A1yx1Ib1SIIFYcD2huDOhWel92xVG9qiKiPG8PhyLdIVqTZ0EvAUJzoTS35rX4hNcg=
