language: r
sudo: false
cache:
  packages: true
  directories:
  - "$TRAVIS_BUILD_DIR/_book"
addons:
   apt:
     packages:
     - libssl-dev
     - libgsl0-dev
before_install:
  - mkdir -p ~/.R
  - echo "CXX14FLAGS=-O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function  -Wno-macro-redefined" >> ~/.R/Makevars
  - echo "CXX14=g++ -std=c++1y -fPIC" >> ~/.R/Makevars
pandoc_version: 1.19.2.1
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- "./_build.sh"
- "./_deploy.sh"
notifications:
  slack:
    secure: EV4fM9uyxKCCsgiNe+tgD87hYgjtVbs+6cdyKywu2y1P+V59KBhSJ9PWoZVJwIMkcEAdTD8BxLk9Na3KGlkowDdfGyEMsVmy/+aKi+jXRRhJW3V7hmj7CWhWXM6nXdqm8iaACaAbJt8yP5HWLBjNcW0JSsA1u3XcH6hsuomnhbyi3MlYz6/qIbPYYl11m4Ok5VnI/v3NjDsrPTcHC7fXP5+fu1rN+WfFplYSP7/p3veXykWdcsB5fM+hovUrBue80w1ozdnppzlNjxH0BbeMHYRKIYPosXn3QS/vBf7t85bBm0GdibRd3aR7H+jVfeNnAH6dE3P7KPmv1bARNLRCcQXNAI+WC+L273XJnzA0wMQNay0CZkAlpLza8HwANtFSUvI8a1qRoB5kQaJzW1UDTiunmwO3BI4qjWdKOqiK4njVMB9LNL4+AFVDwJM1N7UV1f2ZzucVuKSITCI4CzpOyeLS3cc10xFtEiAOSWr4vOXqqDWfM33W9q3ROJ1881mZQbRKgwh3n+KxSp7KvDun9PXEhAZby/CMX88q+BEYjLyvjD5VmbqpTSRfk21Q91Ox6PCcA3Ia9MFP6rjoaoqp2DODYuLHGYhSgk/VehHjgiTj40xK23BKcmqmciOxPrWOpaVDe96n0qPQxJDzu094ytfaWWyL8cne7PKnog3BfKc=
env:
  global:
  - secure: ZTq535hCvbAGcA/YRIOv8fT1RyWlJnyAtxYNvcWQaOhL4YVlEuTSP4ADWRsZ5kT7ksvbQHzzbLYrOlD16C3L2WCD10GBhpFt8qGzO6Cmg6elHfKfyjMwJcqcXgUP3ee83DpaAbOOMLIFmIiXF1ZwIqP1PDnCUUfox1kzYGMi+fc4EvyFXG75qRVWl/uShE95tTz4m4AJ4S7L62rCj0uxNZJArehtwPK2/IqGdEFioqs20P2mQaK2n+nBmJDyOyiAtdQt5xmXe10UpmlEzuvQFcWNvpilZsZu1q7kdLmAoopbHLXRcKXk86tiM6cWiEyGpU1PBrHGGtC9KFNqjFUKxwUfe39tDowtbiXjE8bU04GOtvEN2ohaFgWbyn9CnuNbpyHXnbWorXvlgZXVpTHtaJe/nRVcRX21lwNPhs+7H4LWlLM88wx0T2QLjdflmYigBgcNO4DvTGW/YjhCevSf8UKSoA5sh7l5t25XDOvXnREV2txcBUNHPiDm6NByBV9+1/dEBbARLtv2o8v9jn1R7NbbSyKKLkSfh9I7wqxNYroiYUWIAmK+0Dhn8Y0LV/3ACFIrbxJWBajv+3SJD9bz2GejlJXwM4jdHAyNqkR0nz7ToPIUGWgNNMxYH7An8tvEd9qKnMb/DLQGhJ6Z40GLAugErreuMig7W5h4vGsKNo8=
  - secure: flmfQrvM2Zes/Lb3MR8CdWmJ5r8uC9vtpj2ai8ATKNMUPVnIRAraiQfh0KKVNLr7MMO+sM1RrojqIK/qo47OJHkhUCTQgcQynkapHC1vdxkGFuBhaHbFpyS7vPOVlgS359mXzhqrJJq6aNlDfmcQpmvVQS/gAIXFzJ0/LxbrG8+ROTvCfCDtjEQH9aefKEB8bFDXoY8j19MR7Qyc6wwM5rDz0jBRvN00CEvaQsnNn0GQwC2sua3pT3c6bYUrbMaFpK+XbNBtCjKfiB4gk0XdyiHqVs9tZjgsv9NAinYmhrcs/71UE7teup5TBPw51wBac0Nz8uQqzMgx/S/bwRgL5cB4eCw3nOgAKKp786Qm9NmJiWOFTgyWwNeFbrhzEgKy/BPrvGKM4yMkJ0DWiOsThuI4a4QvfE3Zm7qO/2pEkI/c4Ll/nzz3nf/iKoGw3bG8i1rMhmCYsehkF9qP2PY/zya8b0iGfE53yT/FQC9rtBQjsD+Lt5iMJBebY+nQYHWjitAHYGsw1Q9w1GM67aj50UfRrwpPFOvBVVod07txRDz+5wk0Avi7fw1cW17mqFecd4eVmDyZfWdrvfOLAzVyluaxaJs4jJJHZnR0wu1CyFm+ogt8+gEIjWRVPcda2zWp1MGgSAvQAYK+Z5KErIHOSVWPNADWa2NNKiNMNDxxnX0=
