language: r
sudo: false
dist: trusty
cache:
  packages: true
  directories:
  - $TRAVIS_BUILD_DIR/_book
addons:
  apt:
    packages:
      - libssl-dev
pandoc_version: 1.19.2.1
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- ./_build.sh
- ./_deploy.sh
notifications:
  slack:
    secure: EV4fM9uyxKCCsgiNe+tgD87hYgjtVbs+6cdyKywu2y1P+V59KBhSJ9PWoZVJwIMkcEAdTD8BxLk9Na3KGlkowDdfGyEMsVmy/+aKi+jXRRhJW3V7hmj7CWhWXM6nXdqm8iaACaAbJt8yP5HWLBjNcW0JSsA1u3XcH6hsuomnhbyi3MlYz6/qIbPYYl11m4Ok5VnI/v3NjDsrPTcHC7fXP5+fu1rN+WfFplYSP7/p3veXykWdcsB5fM+hovUrBue80w1ozdnppzlNjxH0BbeMHYRKIYPosXn3QS/vBf7t85bBm0GdibRd3aR7H+jVfeNnAH6dE3P7KPmv1bARNLRCcQXNAI+WC+L273XJnzA0wMQNay0CZkAlpLza8HwANtFSUvI8a1qRoB5kQaJzW1UDTiunmwO3BI4qjWdKOqiK4njVMB9LNL4+AFVDwJM1N7UV1f2ZzucVuKSITCI4CzpOyeLS3cc10xFtEiAOSWr4vOXqqDWfM33W9q3ROJ1881mZQbRKgwh3n+KxSp7KvDun9PXEhAZby/CMX88q+BEYjLyvjD5VmbqpTSRfk21Q91Ox6PCcA3Ia9MFP6rjoaoqp2DODYuLHGYhSgk/VehHjgiTj40xK23BKcmqmciOxPrWOpaVDe96n0qPQxJDzu094ytfaWWyL8cne7PKnog3BfKc=
